name: 'Dockerize'
description: 'Dockerize Python Code'
inputs:
  port:
    description: 'ports to be exposed in your Docker container'
    required: true
    default: 5000
  command:
    description: 'run command for your docker container'
    required: true
runs:
  using: 'composite'
  steps:
    - name: prepare python setup
      run: |
        python -m pip install --upgrade pip
        pip install 
      shell: bash
    - name: run the tracker
      run: python ${{ github.action_path }}/dockerize.py ${{ inputs.port }} ${{ inputs.command }}
      shell: bash